// NULL SAFETYY 


void main() {
  String? name; // NAME NÃO FOI ATRIBUIDO VALOR -> DAI TEM QUE USAR O ?  DAI EU VOU TER USAR ESSA PORRA NO METODO!!, OU USAR O ! COMO GARANTIA QUE NÃO SERÁ NULA!!
  print(name!); // EXCLAMA GARANTE QUE A VARIAVEL NÃO SERÁ NULA!! -> CARAS COMO LATE E TAL!!
}
